# Generated by Django 4.2.2 on 2023-06-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('F', 'Finished'), ('R', 'Running'), ('W', 'Waiting')], default='W', max_length=1)),
            ],
        ),
    ]
